### ISSUE TITLE
Specify Rust version 1.69.0 rather than nightly 

### ISSUE THREAD

**Issue by kigawas** [AstarNetwork/astar-docs#389]
In [ink environment doc](https://github.com/AstarNetwork/astar-docs/blob/main/docs/build/environment/ink_environment.md), it's better to specify 1.69.0 rather than a nightly channel:

```toml
[toolchain]
channel = "1.69.0"
components = [ "rustfmt", "rust-src" ]
targets = [ "wasm32-unknown-unknown" ]
profile = "minimal"
```
